language: python
python:
    - "3.5"
before_install:
    - pip install pytest pytest-cov flask flask-jsonpify flask-restful matplotlib h5py
    - pip install coveralls
script:
    - py.test
after_success:
    - coveralls
