language: python
python:
    - "3.5"
before_script: # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
before_install:
    - pip install pytest pytest-cov flask flask-jsonpify flask-restful matplotlib h5py
    - pip install coveralls
script:
    - py.test
after_success:
    - coveralls
